### ISSUE TITLE
Collection of TODOs

### ISSUE THREAD

**Issue by peterrum** [kronbichler/mf_data_locality#1]
- [x] add GitHub action for checking formatting
- [x] enable Likwid
- [x] add ctest (manufactured solution) and integrate into a GitHub action
- [x] enable to turn off preconditioner (`PreconditionIdentity`)
- [x] add s-step CG
- [x] add pipelined CG

**Comment by shkodm** [comment]
I think this can be closed :slightly_smiling_face:
